# Generated by Django 4.2.4 on 2023-09-07 20:34

from django.db import migrations, models
import utils.generate_code


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code',
            field=models.CharField(default=utils.generate_code.generate_code, max_length=10),
        ),
    ]
