# Generated by Django 4.2.4 on 2023-09-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='flag',
        ),
    ]
